# Spring properties
spring:  banner:    location: classpath:banner.txt  datasource:    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: admin  jpa:    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:      ddl-auto: update
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
server:  error:    whitelabel:      enabled: true